set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MD")
set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG}   /MDd")

set(TARGET_NAME     "${PROJECT_NAME}")

set(SOURCE_FOLDER   "${CMAKE_SOURCE_DIR}/Source")
set(EXTERNAL_FOLDER "${CMAKE_SOURCE_DIR}/.external")
set(SHADERS_FOLDER  "${CMAKE_SOURCE_DIR}/Shaders")
set(OUTPUT_FOLDER   "${CMAKE_BINARY_DIR}/Output")

set(CMAKE_SUPPRESS_REGENERATION true) # Remove "Zero_check" project